import { AppDataSource } from "./src/db/data-source";
import { WaitlistCountry } from "./src/models/waitlist-country";

const rawCountries = `
British Indian Ocean Territory (IO)
Brunei Darussalam (BN)
Burkina Faso (BF)
Burundi (BI)
Cabo Verde (CV)
Cambodia (KH)
Cameroon (CM)
Cayman Islands (KY)
Central African Republic (CF)
Chad (TD)
Chile (CL)
China (CN)
Christmas Island (CX)
Cocos (Keeling) Islands (CC)
Colombia (CO)
Comoros (KM)
Congo (CG)
Congo, Democratic Republic of the (CD)
Cook Islands (CK)
Costa Rica (CR)
Côte d'Ivoire (CI)
Cuba (CU)
Curaçao (CW)
Djibouti (DJ)
Dominica (DM)
Dominican Republic (DO)
Ecuador (EC)
Egypt (EG)
El Salvador (SV)
Equatorial Guinea (GQ)
Eritrea (ER)
Eswatini (SZ)
Ethiopia (ET)
Falkland Islands (Malvinas) (FK)
Faroe Islands (FO)
Fiji (FJ)
French Guiana (GF)
French Polynesia (PF)
French Southern Territories (TF)
Gabon (GA)
Gambia (GM)
Georgia (GE)
Gibraltar (GI)
Greenland (GL)
Grenada (GD)
Guadeloupe (GP)
Guam (GU)
Guatemala (GT)
Guernsey (GG)
Guinea (GN)
Guinea-Bissau (GW)
Guyana (GY)
Haiti (HT)
Heard Island and McDonald Islands (HM)
Holy See (Vatican City) (VA)
Honduras (HN)
Hong Kong (HK)
Iceland (IS)
India (IN)
Indonesia (ID)
Iran (IR)
Iraq (IQ)
Isle of Man (IM)
Israel (IL)
Jamaica (JM)
Japan (JP)
Jersey (JE)
Jordan (JO)
Kazakhstan (KZ)
Kiribati (KI)
Korea, Democratic People's Republic of (KP)
Korea, Republic of (KR)
Kuwait (KW)
Kyrgyzstan (KG)
Lao People's Democratic Republic (LA)
Lebanon (LB)
Lesotho (LS)
Liberia (LR)
Libya (LY)
Liechtenstein (LI)
Macao (MO)
Madagascar (MG)
Malawi (MW)
Malaysia (MY)
Maldives (MV)
Mali (ML)
Marshall Islands (MH)
Martinique (MQ)
Mauritania (MR)
Mauritius (MU)
Mayotte (YT)
Mexico (MX)
Micronesia (Federated States of) (FM)
Moldova (MD)
Monaco (MC)
Mongolia (MN)
Montenegro (ME)
Montserrat (MS)
Morocco (MA)
Mozambique (MZ)
Myanmar (MM)
Namibia (NA)
Nauru (NR)
Nepal (NP)
New Caledonia (NC)
New Zealand (NZ)
Nicaragua (NI)
Niger (NE)
North Macedonia (MK)
Norway (NO)
Oman (OM)
Pakistan (PK)
Palau (PW)
Palestine, State of (PS)
Papua New Guinea (PG)
Paraguay (PY)
Peru (PE)
Philippines (PH)
Pitcairn (PN)
Puerto Rico (PR)
Qatar (QA)
Réunion (RE)
Russian Federation (RU)
Rwanda (RW)
Saint Barthélemy (BL)
Saint Helena, Ascension and Tristan da Cunha (SH)
Saint Kitts and Nevis (KN)
Saint Lucia (LC)
Saint Martin (French part) (MF)
Saint Pierre and Miquelon (PM)
Saint Vincent and the Grenadines (VC)
Samoa (WS)
San Marino (SM)
Sao Tome and Principe (ST)
Saudi Arabia (SA)
Serbia (RS)
Seychelles (SC)
Sierra Leone (SL)
Singapore (SG)
Sint Maarten (Dutch part) (SX)
Solomon Islands (SB)
Somalia (SO)
South Georgia and the South Sandwich Islands (GS)
South Sudan (SS)
Sri Lanka (LK)
Sudan (SD)
Suriname (SR)
Svalbard and Jan Mayen (SJ)
Switzerland (CH)
Syrian Arab Republic (SY)
Taiwan (Province of China) (TW)
Tajikistan (TJ)
Thailand (TH)
Timor-Leste (TL)
Tokelau (TK)
Tonga (TO)
Trinidad and Tobago (TT)
Tunisia (TN)
Türkiye (TR)
Turkmenistan (TM)
Turks and Caicos Islands (TC)
Tuvalu (TV)
Uganda (UG)
Ukraine (UA)
United Arab Emirates (AE)
United Kingdom (GB)
United States Minor Outlying Islands (UM)
Uruguay (UY)
Uzbekistan (UZ)
Vanuatu (VU)
Venezuela (VE)
Viet Nam (VN)
Virgin Islands (British) (VG)
Virgin Islands (U.S.) (VI)
Wallis and Futuna (WF)
Western Sahara (EH)
Yemen (YE)
Zambia (ZM)
Zimbabwe (ZW)
`;

async function seed() {
    await AppDataSource.initialize();
    const repo = AppDataSource.getRepository(WaitlistCountry);

    const lines = rawCountries.split("\n").filter(l => l.trim().length > 0);
    let count = 0;

    for (const line of lines) {
        const match = line.match(/(.+)\s\(([A-Z]{2,4})\)/);
        if (match) {
            const name = match[1].trim();
            const code = match[2];

            const existing = await repo.findOneBy({ code });
            if (!existing) {
                const country = repo.create({
                    name,
                    code,
                    isActive: true
                });
                await repo.save(country);
                count++;
            }
        }
    }

    console.log(`Seeded ${count} new countries.`);
    await AppDataSource.destroy();
}

seed().catch(console.error);
